tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'caskroom/cask'
tap 'caskroom/fonts'

cask 'dropbox'

brew 'gdal'
brew 'git'
brew 'heroku'
brew 'hub'
brew 'imagemagick'
brew 'macvim', args: ['with-override-system-vim']
brew 'node'
brew 'phantomjs'
brew 'postgresql'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'rename'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tmux'
brew 'unrar'
brew 'wget'
brew 'zsh'

cask '1password'
cask 'appcleaner'
cask 'arq'
cask 'atom'
cask 'beamer'
cask 'choosy'
cask 'dash'
cask 'disk-inventory-x'
cask 'firefox'
cask 'google-chrome'
cask 'harvest'
cask 'sketch'
cask 'skype'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'subtitles'
cask 'transmission'
cask 'vlc'

cask 'font-source-code-pro'
