cask 'dropbox'

brew 'bat'
brew 'eza'
brew 'fzf'
brew 'git'
brew 'gpg'
brew 'mas'
brew 'mise'
brew 'neovim'
brew 'ripgrep'
brew 'tmux'
brew 'wget'
brew 'yt-dlp'
brew 'zoxide'
brew 'zsh'
brew 'zsh-autosuggestions'

cask '1password'
cask 'appcleaner'
cask 'choosy'
cask 'emacs-app'
cask 'figma'
cask 'firefox'
cask 'google-chrome'
cask 'hammerspoon'
cask 'iina'
cask 'karabiner-elements'
cask 'keepingyouawake'
cask 'kitty'
cask 'monitorcontrol' # for Dell monitor
cask 'notion'
cask 'slack'
cask 'spotify'
cask 'transmission'
cask 'tunnelblick'
cask 'visual-studio-code'
cask 'whatsapp'

cask 'font-sauce-code-pro-nerd-font'

mas "Ghostery Privacy Ad Blocker", id: 6504861501
mas "Xcode", id: 497799835
mas "Simplenote", id: 692867256
mas "1Password for Safari", id: 1569813296
