tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-drivers'
tap 'homebrew/services'

cask 'dropbox'

brew 'asdf'
brew 'fzf'
brew 'git'
brew 'gpg'
brew 'macvim'
brew 'mas'
brew 'ripgrep'
brew 'subliminal'
brew 'tmux'
brew 'wget'
brew 'yt-dlp'
brew 'zsh'

cask '1password'
cask 'adoptopenjdk'
cask 'appcleaner'
cask 'choosy'
cask 'emacs'
cask 'figma'
cask 'firefox'
cask 'google-chrome'
cask 'karabiner-elements'
cask 'keepingyouawake'
cask 'mullvadvpn'
cask 'notion'
cask 'obinskit'
cask 'simplenote'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'

brew 'svn' # Needed for fonts
cask 'font-source-code-pro'
cask 'font-overpass'

mas "Ghostery – Privacy Ad Blocker", id: 1436953057
mas "Pixelmator", id: 407963104
mas "Save to Pocket", id: 1477385213
mas "Xcode", id: 497799835
